server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CALIBER_CONFIG_GIT_URI}
          username: ${CALIBER_CONFIG_GIT_USERNAME}
          password: ${CALIBER_CONFIG_GIT_PASSWORD}
  application:
    name: caliber-config
    